"""Initial migration

Revision ID: 8cac37665b44
Revises:
Create Date: 2026-03-24 16:29:55.711218

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer


# revision identifiers, used by Alembic.
revision: str = '8cac37665b44'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'parcel_types',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'parcels',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('session_id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('weight', sa.Float(), nullable=False),
        sa.Column('price_usd', sa.Float(), nullable=False),
        sa.Column('delivery_cost_rub', sa.Float(), nullable=True),
        sa.Column('type_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['type_id'],
            ['parcel_types.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    parcel_types_table = table(
        'parcel_types', column('id', Integer), column('name', String)
    )

    op.bulk_insert(
        parcel_types_table,
        [
            {'id': 1, 'name': 'одежда'},
            {'id': 2, 'name': 'электроника'},
            {'id': 3, 'name': 'разное'},
        ],
    )
    op.create_index(
        op.f('ix_parcels_session_id'), 'parcels', ['session_id'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parcels_session_id'), table_name='parcels')
    op.drop_table('parcels')
    op.drop_table('parcel_types')
    # ### end Alembic commands ###
